// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kgateway-dev/kgateway/v2/pkg/kgateway/query (interfaces: GatewayQueries)
//
// Generated by this command:
//
//	mockgen -destination mocks/mock_queries.go -package mocks github.com/kgateway-dev/kgateway/v2/pkg/kgateway/query GatewayQueries
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	query "github.com/kgateway-dev/kgateway/v2/pkg/kgateway/query"
	ir "github.com/kgateway-dev/kgateway/v2/pkg/pluginsdk/ir"
	gomock "go.uber.org/mock/gomock"
	krt "istio.io/istio/pkg/kube/krt"
	v1 "k8s.io/api/core/v1"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	v10 "sigs.k8s.io/gateway-api/apis/v1"
)

// MockGatewayQueries is a mock of GatewayQueries interface.
type MockGatewayQueries struct {
	ctrl     *gomock.Controller
	recorder *MockGatewayQueriesMockRecorder
	isgomock struct{}
}

// MockGatewayQueriesMockRecorder is the mock recorder for MockGatewayQueries.
type MockGatewayQueriesMockRecorder struct {
	mock *MockGatewayQueries
}

// NewMockGatewayQueries creates a new mock instance.
func NewMockGatewayQueries(ctrl *gomock.Controller) *MockGatewayQueries {
	mock := &MockGatewayQueries{ctrl: ctrl}
	mock.recorder = &MockGatewayQueriesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGatewayQueries) EXPECT() *MockGatewayQueriesMockRecorder {
	return m.recorder
}

// GetConfigMapForRef mocks base method.
func (m *MockGatewayQueries) GetConfigMapForRef(kctx krt.HandlerContext, ctx context.Context, fromGk schema.GroupKind, fromns string, configMapRef v10.ObjectReference) (*v1.ConfigMap, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfigMapForRef", kctx, ctx, fromGk, fromns, configMapRef)
	ret0, _ := ret[0].(*v1.ConfigMap)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConfigMapForRef indicates an expected call of GetConfigMapForRef.
func (mr *MockGatewayQueriesMockRecorder) GetConfigMapForRef(kctx, ctx, fromGk, fromns, configMapRef any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfigMapForRef", reflect.TypeOf((*MockGatewayQueries)(nil).GetConfigMapForRef), kctx, ctx, fromGk, fromns, configMapRef)
}

// GetRouteChain mocks base method.
func (m *MockGatewayQueries) GetRouteChain(kctx krt.HandlerContext, ctx context.Context, route ir.Route, hostnames []string, parentRef v10.ParentReference) *query.RouteInfo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRouteChain", kctx, ctx, route, hostnames, parentRef)
	ret0, _ := ret[0].(*query.RouteInfo)
	return ret0
}

// GetRouteChain indicates an expected call of GetRouteChain.
func (mr *MockGatewayQueriesMockRecorder) GetRouteChain(kctx, ctx, route, hostnames, parentRef any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRouteChain", reflect.TypeOf((*MockGatewayQueries)(nil).GetRouteChain), kctx, ctx, route, hostnames, parentRef)
}

// GetRoutesForGateway mocks base method.
func (m *MockGatewayQueries) GetRoutesForGateway(kctx krt.HandlerContext, ctx context.Context, gw *ir.Gateway) (*query.RoutesForGwResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoutesForGateway", kctx, ctx, gw)
	ret0, _ := ret[0].(*query.RoutesForGwResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRoutesForGateway indicates an expected call of GetRoutesForGateway.
func (mr *MockGatewayQueriesMockRecorder) GetRoutesForGateway(kctx, ctx, gw any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoutesForGateway", reflect.TypeOf((*MockGatewayQueries)(nil).GetRoutesForGateway), kctx, ctx, gw)
}

// GetSecretForRef mocks base method.
func (m *MockGatewayQueries) GetSecretForRef(kctx krt.HandlerContext, ctx context.Context, fromGk schema.GroupKind, fromns string, secretRef v10.SecretObjectReference) (*ir.Secret, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSecretForRef", kctx, ctx, fromGk, fromns, secretRef)
	ret0, _ := ret[0].(*ir.Secret)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSecretForRef indicates an expected call of GetSecretForRef.
func (mr *MockGatewayQueriesMockRecorder) GetSecretForRef(kctx, ctx, fromGk, fromns, secretRef any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSecretForRef", reflect.TypeOf((*MockGatewayQueries)(nil).GetSecretForRef), kctx, ctx, fromGk, fromns, secretRef)
}
