version: 2
updates:
  # v2.3.x - current main branch. Update this when we create a new branch for 2.3.x
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "area/ci"

  - package-ecosystem: "docker"
    directories:
      - "/cmd/envoyinit"
      - "/cmd/kgateway"
      - "/cmd/sds"
      - "/hack/dummy-idp"
      - "/tools/build-tools"
      - "/test/e2e/defaults/extproc"
      - "/test/e2e/testutils/helper/docker"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "area/ci"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "area/ci"

  # v2.2.x
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "v2.2.x"
    labels:
      - "dependencies"
      - "area/ci"

  - package-ecosystem: "docker"
    directories:
      - "/cmd/envoyinit"
      - "/cmd/kgateway"
      - "/cmd/sds"
      - "/hack/dummy-idp"
      - "/test/e2e/features/agentgateway/a2a/example"
      - "/test/e2e/features/agentgateway/extproc/example"
      - "/test/e2e/features/agentgateway/mcp"
      - "/test/e2e/testutils/helper/docker"
    schedule:
      interval: "weekly"
    target-branch: "v2.2.x"
    labels:
      - "dependencies"
      - "area/ci"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "v2.2.x"
    labels:
      - "dependencies"
      - "area/ci"

  # v2.1.x
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "v2.1.x"
    labels:
      - "dependencies"
      - "area/ci"

  - package-ecosystem: "docker"
    directories:
      - "/cmd/envoyinit"
      - "/cmd/kgateway"
      - "/cmd/sds"
      - "/python"
      - "/test/kubernetes/e2e/features/agentgateway/a2a/example"
      - "/test/kubernetes/e2e/features/agentgateway/mcp"
      - "/test/kubernetes/testutils/helper/docker"
      - "/test/mocks/mock-ai-provider-server"
    schedule:
      interval: "weekly"
    target-branch: "v2.1.x"
    labels:
      - "dependencies"
      - "area/ci"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "v2.1.x"
    labels:
      - "dependencies"
      - "area/ci"