// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// MCPAuthPolicyStatusApplyConfiguration represents a declarative configuration of the MCPAuthPolicyStatus type for use
// with apply.
type MCPAuthPolicyStatusApplyConfiguration struct {
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
}

// MCPAuthPolicyStatusApplyConfiguration constructs a declarative configuration of the MCPAuthPolicyStatus type for use with
// apply.
func MCPAuthPolicyStatus() *MCPAuthPolicyStatusApplyConfiguration {
	return &MCPAuthPolicyStatusApplyConfiguration{}
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *MCPAuthPolicyStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *MCPAuthPolicyStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
