// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// MCPAuthPolicyMatchServiceAccountApplyConfiguration represents a declarative configuration of the MCPAuthPolicyMatchServiceAccount type for use
// with apply.
type MCPAuthPolicyMatchServiceAccountApplyConfiguration struct {
	Name      *string `json:"name,omitempty"`
	Namespace *string `json:"namespace,omitempty"`
}

// MCPAuthPolicyMatchServiceAccountApplyConfiguration constructs a declarative configuration of the MCPAuthPolicyMatchServiceAccount type for use with
// apply.
func MCPAuthPolicyMatchServiceAccount() *MCPAuthPolicyMatchServiceAccountApplyConfiguration {
	return &MCPAuthPolicyMatchServiceAccountApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *MCPAuthPolicyMatchServiceAccountApplyConfiguration) WithName(value string) *MCPAuthPolicyMatchServiceAccountApplyConfiguration {
	b.Name = &value
	return b
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *MCPAuthPolicyMatchServiceAccountApplyConfiguration) WithNamespace(value string) *MCPAuthPolicyMatchServiceAccountApplyConfiguration {
	b.Namespace = &value
	return b
}
