// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// MCPAuthPolicyMatchJWTApplyConfiguration represents a declarative configuration of the MCPAuthPolicyMatchJWT type for use
// with apply.
type MCPAuthPolicyMatchJWTApplyConfiguration struct {
	Claim *string `json:"claim,omitempty"`
	Value *string `json:"value,omitempty"`
}

// MCPAuthPolicyMatchJWTApplyConfiguration constructs a declarative configuration of the MCPAuthPolicyMatchJWT type for use with
// apply.
func MCPAuthPolicyMatchJWT() *MCPAuthPolicyMatchJWTApplyConfiguration {
	return &MCPAuthPolicyMatchJWTApplyConfiguration{}
}

// WithClaim sets the Claim field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Claim field is set to the value of the last call.
func (b *MCPAuthPolicyMatchJWTApplyConfiguration) WithClaim(value string) *MCPAuthPolicyMatchJWTApplyConfiguration {
	b.Claim = &value
	return b
}

// WithValue sets the Value field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Value field is set to the value of the last call.
func (b *MCPAuthPolicyMatchJWTApplyConfiguration) WithValue(value string) *MCPAuthPolicyMatchJWTApplyConfiguration {
	b.Value = &value
	return b
}
