// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/kgateway-dev/kgateway/v2/api/v1alpha1"
)

// MCPAuthPolicyMatchApplyConfiguration represents a declarative configuration of the MCPAuthPolicyMatch type for use
// with apply.
type MCPAuthPolicyMatchApplyConfiguration struct {
	Type           *apiv1alpha1.MCPAuthPolicyMatchType                 `json:"type,omitempty"`
	JWT            *MCPAuthPolicyMatchJWTApplyConfiguration            `json:"jwt,omitempty"`
	ServiceAccount *MCPAuthPolicyMatchServiceAccountApplyConfiguration `json:"serviceAccount,omitempty"`
}

// MCPAuthPolicyMatchApplyConfiguration constructs a declarative configuration of the MCPAuthPolicyMatch type for use with
// apply.
func MCPAuthPolicyMatch() *MCPAuthPolicyMatchApplyConfiguration {
	return &MCPAuthPolicyMatchApplyConfiguration{}
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *MCPAuthPolicyMatchApplyConfiguration) WithType(value apiv1alpha1.MCPAuthPolicyMatchType) *MCPAuthPolicyMatchApplyConfiguration {
	b.Type = &value
	return b
}

// WithJWT sets the JWT field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the JWT field is set to the value of the last call.
func (b *MCPAuthPolicyMatchApplyConfiguration) WithJWT(value *MCPAuthPolicyMatchJWTApplyConfiguration) *MCPAuthPolicyMatchApplyConfiguration {
	b.JWT = value
	return b
}

// WithServiceAccount sets the ServiceAccount field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServiceAccount field is set to the value of the last call.
func (b *MCPAuthPolicyMatchApplyConfiguration) WithServiceAccount(value *MCPAuthPolicyMatchServiceAccountApplyConfiguration) *MCPAuthPolicyMatchApplyConfiguration {
	b.ServiceAccount = value
	return b
}
