// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// MCPResourceApplyConfiguration represents a declarative configuration of the MCPResource type for use
// with apply.
type MCPResourceApplyConfiguration struct {
	Kind *string `json:"kind,omitempty"`
	Name *string `json:"name,omitempty"`
}

// MCPResourceApplyConfiguration constructs a declarative configuration of the MCPResource type for use with
// apply.
func MCPResource() *MCPResourceApplyConfiguration {
	return &MCPResourceApplyConfiguration{}
}

// WithKind sets the Kind field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kind field is set to the value of the last call.
func (b *MCPResourceApplyConfiguration) WithKind(value string) *MCPResourceApplyConfiguration {
	b.Kind = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *MCPResourceApplyConfiguration) WithName(value string) *MCPResourceApplyConfiguration {
	b.Name = &value
	return b
}
