// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// MCPRouteStatusApplyConfiguration represents a declarative configuration of the MCPRouteStatus type for use
// with apply.
type MCPRouteStatusApplyConfiguration struct {
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
}

// MCPRouteStatusApplyConfiguration constructs a declarative configuration of the MCPRouteStatus type for use with
// apply.
func MCPRouteStatus() *MCPRouteStatusApplyConfiguration {
	return &MCPRouteStatusApplyConfiguration{}
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *MCPRouteStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *MCPRouteStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
