// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	gentype "k8s.io/client-go/gentype"

	apiv1alpha1 "github.com/kgateway-dev/kgateway/v2/api/applyconfiguration/api/v1alpha1"
	v1alpha1 "github.com/kgateway-dev/kgateway/v2/api/v1alpha1"
	typedapiv1alpha1 "github.com/kgateway-dev/kgateway/v2/pkg/client/clientset/versioned/typed/api/v1alpha1"
)

// fakeMCPAuthPolicies implements MCPAuthPolicyInterface
type fakeMCPAuthPolicies struct {
	*gentype.FakeClientWithListAndApply[*v1alpha1.MCPAuthPolicy, *v1alpha1.MCPAuthPolicyList, *apiv1alpha1.MCPAuthPolicyApplyConfiguration]
	Fake *FakeGatewayV1alpha1
}

func newFakeMCPAuthPolicies(fake *FakeGatewayV1alpha1, namespace string) typedapiv1alpha1.MCPAuthPolicyInterface {
	return &fakeMCPAuthPolicies{
		gentype.NewFakeClientWithListAndApply[*v1alpha1.MCPAuthPolicy, *v1alpha1.MCPAuthPolicyList, *apiv1alpha1.MCPAuthPolicyApplyConfiguration](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("mcpauthpolicies"),
			v1alpha1.SchemeGroupVersion.WithKind("MCPAuthPolicy"),
			func() *v1alpha1.MCPAuthPolicy { return &v1alpha1.MCPAuthPolicy{} },
			func() *v1alpha1.MCPAuthPolicyList { return &v1alpha1.MCPAuthPolicyList{} },
			func(dst, src *v1alpha1.MCPAuthPolicyList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.MCPAuthPolicyList) []*v1alpha1.MCPAuthPolicy {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.MCPAuthPolicyList, items []*v1alpha1.MCPAuthPolicy) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
