// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	gentype "k8s.io/client-go/gentype"

	apiv1alpha1 "github.com/kgateway-dev/kgateway/v2/api/applyconfiguration/api/v1alpha1"
	v1alpha1 "github.com/kgateway-dev/kgateway/v2/api/v1alpha1"
	typedapiv1alpha1 "github.com/kgateway-dev/kgateway/v2/pkg/client/clientset/versioned/typed/api/v1alpha1"
)

// fakeMCPRoutes implements MCPRouteInterface
type fakeMCPRoutes struct {
	*gentype.FakeClientWithListAndApply[*v1alpha1.MCPRoute, *v1alpha1.MCPRouteList, *apiv1alpha1.MCPRouteApplyConfiguration]
	Fake *FakeGatewayV1alpha1
}

func newFakeMCPRoutes(fake *FakeGatewayV1alpha1, namespace string) typedapiv1alpha1.MCPRouteInterface {
	return &fakeMCPRoutes{
		gentype.NewFakeClientWithListAndApply[*v1alpha1.MCPRoute, *v1alpha1.MCPRouteList, *apiv1alpha1.MCPRouteApplyConfiguration](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("mcproutes"),
			v1alpha1.SchemeGroupVersion.WithKind("MCPRoute"),
			func() *v1alpha1.MCPRoute { return &v1alpha1.MCPRoute{} },
			func() *v1alpha1.MCPRouteList { return &v1alpha1.MCPRouteList{} },
			func(dst, src *v1alpha1.MCPRouteList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.MCPRouteList) []*v1alpha1.MCPRoute { return gentype.ToPointerSlice(list.Items) },
			func(list *v1alpha1.MCPRouteList, items []*v1alpha1.MCPRoute) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
