// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"

	applyconfigurationapiv1alpha1 "github.com/kgateway-dev/kgateway/v2/api/applyconfiguration/api/v1alpha1"
	apiv1alpha1 "github.com/kgateway-dev/kgateway/v2/api/v1alpha1"
	scheme "github.com/kgateway-dev/kgateway/v2/pkg/client/clientset/versioned/scheme"
)

// MCPRoutesGetter has a method to return a MCPRouteInterface.
// A group's client should implement this interface.
type MCPRoutesGetter interface {
	MCPRoutes(namespace string) MCPRouteInterface
}

// MCPRouteInterface has methods to work with MCPRoute resources.
type MCPRouteInterface interface {
	Create(ctx context.Context, mCPRoute *apiv1alpha1.MCPRoute, opts v1.CreateOptions) (*apiv1alpha1.MCPRoute, error)
	Update(ctx context.Context, mCPRoute *apiv1alpha1.MCPRoute, opts v1.UpdateOptions) (*apiv1alpha1.MCPRoute, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, mCPRoute *apiv1alpha1.MCPRoute, opts v1.UpdateOptions) (*apiv1alpha1.MCPRoute, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*apiv1alpha1.MCPRoute, error)
	List(ctx context.Context, opts v1.ListOptions) (*apiv1alpha1.MCPRouteList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *apiv1alpha1.MCPRoute, err error)
	Apply(ctx context.Context, mCPRoute *applyconfigurationapiv1alpha1.MCPRouteApplyConfiguration, opts v1.ApplyOptions) (result *apiv1alpha1.MCPRoute, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, mCPRoute *applyconfigurationapiv1alpha1.MCPRouteApplyConfiguration, opts v1.ApplyOptions) (result *apiv1alpha1.MCPRoute, err error)
	MCPRouteExpansion
}

// mCPRoutes implements MCPRouteInterface
type mCPRoutes struct {
	*gentype.ClientWithListAndApply[*apiv1alpha1.MCPRoute, *apiv1alpha1.MCPRouteList, *applyconfigurationapiv1alpha1.MCPRouteApplyConfiguration]
}

// newMCPRoutes returns a MCPRoutes
func newMCPRoutes(c *GatewayV1alpha1Client, namespace string) *mCPRoutes {
	return &mCPRoutes{
		gentype.NewClientWithListAndApply[*apiv1alpha1.MCPRoute, *apiv1alpha1.MCPRouteList, *applyconfigurationapiv1alpha1.MCPRouteApplyConfiguration](
			"mcproutes",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *apiv1alpha1.MCPRoute { return &apiv1alpha1.MCPRoute{} },
			func() *apiv1alpha1.MCPRouteList { return &apiv1alpha1.MCPRouteList{} },
		),
	}
}
