apiVersion: gateway.networking.k8s.io/v1
kind: BackendTLSPolicy
metadata:
  name: tlsroute-backend-tls
spec:
  targetRefs:
  - group: ""
    kind: Service
    name: example-tls-svc
  validation:
    hostname: "example.com"
    wellKnownCACertificates: System
