# Filter-level rate limiting via ExtensionRef
# Tests rate limiting attached via HTTPRoute filter ExtensionRef (no targetRef needed)
apiVersion: gateway.kgateway.dev/v1alpha1
kind: TrafficPolicy
metadata:
  name: ratelimit-for-extension-ref
  namespace: infra
spec:
  rateLimit:
    global:
      descriptors:
      - entries:
        - type: Header
          header: "X-Filter-ID"
      extensionRef: 
        name: basic-ratelimit
---
# Gateway extension for route-level rate limiting
# Used when rate limiting is applied to HTTPRoutes
apiVersion: gateway.kgateway.dev/v1alpha1
kind: GatewayExtension
metadata:
  name: basic-ratelimit
  namespace: infra
spec:
  type: RateLimit
  rateLimit:
    grpcService:
      backendRef:
        name: ratelimit
        port: 8081
    domain: "api-gateway-routes"
    timeout: "150ms"
