kind: Gateway
apiVersion: gateway.networking.k8s.io/v1
metadata:
  name: example-gateway
spec:
  gatewayClassName: kgateway
  listeners:
    - protocol: HTTP
      port: 8080
      name: http
      allowedRoutes:
        namespaces:
          from: Same
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: example-route
spec:
  parentRefs:
    - name: example-gateway
  hostnames:
    - "www.example.com"
  rules:
    - filters:
      - type: ExtensionRef
        extensionRef:
          name: test-1
          group: gateway.kgateway.dev
          kind: DirectResponse
      - type: ExtensionRef
        extensionRef:
          name: test-2
          group: gateway.kgateway.dev
          kind: DirectResponse
---
apiVersion: gateway.kgateway.dev/v1alpha1
kind: DirectResponse
metadata:
  name: test-1
spec:
  status: 301
  body: "Test 1 body"
---
apiVersion: gateway.kgateway.dev/v1alpha1
kind: DirectResponse
metadata:
  name: test-2
spec:
  status: 302
  body: "Test 2 body"