apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: example-gateway
  namespace: default
spec:
  gatewayClassName: example-gateway-class
  listeners:
  - name: http
    protocol: HTTP
    port: 80
  - name: http2
    protocol: HTTP
    port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: example-svc
  namespace: default
spec:
  selector:
    test: test
  ports:
    - protocol: TCP
      port: 80
      targetPort: test
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: example-route
  namespace: default
spec:
  parentRefs:
  - name: example-gateway
  hostnames:
  - "example.com"
  rules:
  - backendRefs:
    - name: example-svc
      port: 80
---
apiVersion: gateway.kgateway.dev/v1alpha1
kind: ListenerPolicy
metadata:
  name: rbac-network-per-port
  namespace: default
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: example-gateway
  default:
    rbac:
      action: Allow
      policy:
        matchExpressions:
          - 'source.address.startsWith("10.0.0.")'
  perPort:
    - port: 8080
      listener:
        rbac:
          action: Deny
          policy:
            matchExpressions:
              - 'source.address.startsWith("192.168.0.")'
