#!/usr/bin/env bash
# Render Dockerfile.tmpl by auto-discovering workspace crate members from Cargo.toml.
# Usage: generate-dockerfile.sh <envoy_modules_dir> <template> <output>
# Called by the Makefile when building the envoyinit Docker image.

set -euo pipefail

ENVOY_MODULES_DIR="${1%/}"  # strip any trailing slash
TEMPLATE="${2}"
OUTPUT="${3}"
WORKSPACE_TOML="$ENVOY_MODULES_DIR/Cargo.toml"

if [ ! -f "$WORKSPACE_TOML" ]; then
    echo "Error: workspace Cargo.toml not found at $WORKSPACE_TOML" >&2
    exit 1
fi

# Extract workspace members from the [workspace] members array.
# Handles the standard multi-line array format produced by cargo/rustfmt.
members=$(sed -n '/^members = \[/,/^\]/p' "$WORKSPACE_TOML" | sed -n 's/.*"\([^"]*\)".*/\1/p')

if [ -z "$members" ]; then
    echo "Error: no workspace members found in $WORKSPACE_TOML" >&2
    exit 1
fi

# get_lib_name <cargo_toml>
# Returns the library artifact name for a crate.
# Prefers [lib] name = "..." over [package] name = "..." (with - replaced by _).
get_lib_name() {
    awk '
        /^\[lib\]/     { in_lib=1; in_pkg=0; next }
        /^\[package\]/ { in_pkg=1; in_lib=0; next }
        /^\[/          { in_lib=0; in_pkg=0; next }
        in_lib && /^name = / {
            sub(/^name = "/, ""); sub(/".*$/, "")
            lib_name = $0; found_lib = 1; in_lib = 0
        }
        in_pkg && /^name = / {
            sub(/^name = "/, ""); sub(/".*$/, "")
            gsub(/-/, "_"); pkg_name = $0; in_pkg = 0
        }
        END { print (found_lib ? lib_name : pkg_name) }
    ' "$1"
}

# is_cdylib <cargo_toml> — returns 0 (true) if crate produces a .so
# Use -E (ERE) so '|' alternation works under both GNU and BSD grep (macOS).
is_cdylib() {
    grep -Eq 'crate-type.*cdylib|cdylib.*crate-type' "$1"
}

TMPDIR_GENERATED=$(mktemp -d)
trap 'rm -rf "$TMPDIR_GENERATED"' EXIT

# Section 1: RUN mkdir -p ... && echo "pub fn dummy() {}" > ...
{
    first=true
    for member in $members; do
        if [ "$first" = true ]; then
            printf 'RUN mkdir -p %s/src' "$member"
            first=false
        else
            printf ' \\\n              %s/src' "$member"
        fi
    done
    for member in $members; do
        printf ' \\\n    && echo "pub fn dummy() {}" > %s/src/lib.rs' "$member"
    done
    printf '\n'
} > "$TMPDIR_GENERATED/crate_dummy_setup"

# Section 2: COPY ${ENVOY_MODULES_DIR}/<member>/Cargo.toml ./<member>
{
    for member in $members; do
        printf 'COPY ${ENVOY_MODULES_DIR}/%s/Cargo.toml ./%s\n' "$member" "$member"
    done
} > "$TMPDIR_GENERATED/crate_cargo_copy"

# Section 3: RUN cargo fetch && cargo zigbuild && find ... -delete
{
    printf 'RUN cargo fetch \\\n'
    printf '    && cargo zigbuild --target ${RUST_BUILD_ARCH}-unknown-linux-gnu \\\n'
    printf '    && find /build/target \\( '
    first=true
    for member in $members; do
        cargo_toml="$ENVOY_MODULES_DIR/$member/Cargo.toml"
        lib_name=$(get_lib_name "$cargo_toml")
        if is_cdylib "$cargo_toml"; then
            pat="lib${lib_name}.so"
        else
            pat="'lib${lib_name}-*.rlib'"
        fi
        if [ "$first" = true ]; then
            printf -- '-name %s \\\n' "$pat"
            first=false
        else
            printf '        -o -name %s \\\n' "$pat"
        fi
    done
    printf '    \\) -type f -delete\n'
} > "$TMPDIR_GENERATED/crate_cache_bust_run"

temp_output=$(mktemp)
cat << EOF > "$temp_output"
###################################################################################################
# This file is generated by cmd/envoyinit/generate-dockerfile.sh when the 'envoy-wrapper-docker'  #
# or 'generate-all' make target is run.                                                           #
# DO NOT EDIT BY HAND! Edit cmd/envoyinit/Dockerfile.tmpl instead.                                #
###################################################################################################
EOF
if [ $? != 0 ]; then
    echo "failed to create tempfile $temp_output"
    exit 1
fi
# Replace markers in the template using sed's r (read file) command.
sed \
    -e "/^# __CRATE_DUMMY_SETUP__$/r $TMPDIR_GENERATED/crate_dummy_setup" \
    -e "/^# __CRATE_DUMMY_SETUP__$/d" \
    -e "/^# __CRATE_CARGO_COPY__$/r $TMPDIR_GENERATED/crate_cargo_copy" \
    -e "/^# __CRATE_CARGO_COPY__$/d" \
    -e "/^# __CRATE_CACHE_BUST_RUN__$/r $TMPDIR_GENERATED/crate_cache_bust_run" \
    -e "/^# __CRATE_CACHE_BUST_RUN__$/d" \
    "$TEMPLATE" >> "$temp_output"
if [ $? != 0 ]; then
    echo "failed to generate Dockerfile from $TEMPLATE"
    exit 1
fi

mv "$temp_output" "$OUTPUT"
if [ $? != 0 ]; then
    echo "failed to move $temp_output to $OUTPUT"
    exit 1
fi
