apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: example-gateway
  namespace: default
spec:
  gatewayClassName: example-gateway-class
  listeners:
  - name: http
    protocol: HTTP
    port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ec2-route
  namespace: default
spec:
  parentRefs:
    - name: example-gateway
  hostnames:
    - "ec2.example.com"
  rules:
    - matches:
      - path:
          type: Exact
          value: /ec2
      backendRefs:
        - name: ec2-backend
          kind: Backend
          group: gateway.kgateway.dev
---
apiVersion: gateway.kgateway.dev/v1alpha1
kind: Backend
metadata:
  name: ec2-backend
  namespace: default
spec:
  type: AWS
  aws:
    region: us-east-1
    auth:
      type: Secret
      secretRef:
        name: aws-creds
    ec2:
      port: 8080
      addressType: PrivateIP
      roleArn: arn:aws:iam::123456789012:role/describe-ec2
      filters:
      - keyValue:
          key: app
          value: payments
---
apiVersion: v1
kind: Secret
metadata:
  name: aws-creds
  namespace: default
type: Opaque
data:
  accessKey: QUtJQUlPU0ZPRE5ON0VYQU1QTEU=
  secretKey: d0phbHJYVXRuRkVNSS9LN01ERU5HL2JQeFJmaUNZRVhBTVBMRUtFWQ==
