name: Regression Tests
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  merge_group:
    types: [checks_requested]

env:
  VERSION: '1.0.0-ci1'
  GITHUB_TOKEN: ${{ github.token }} # necessary to pass upgrade tests

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  kube_gateway_api_conformance_tests:
    name: k8s gw API conformance (gw-api=${{matrix.gateway-api-version.version}}-${{matrix.gateway-api-version.channel}})
    runs-on: ubuntu-22.04
    timeout-minutes: 60
    if: ${{ !github.event.pull_request.draft }}
    strategy:
      fail-fast: false
      matrix:
        kube-version: [ { node: 'v1.34.0@sha256:7416a61b42b1662ca6ca89f02028ac133a309a2a30ba309614e8ec94d976dc5a', kubectl: 'v1.34.1', kind: 'v0.30.0' } ]
        gateway-api-version: [ { version: 'v1.4.0', channel: 'experimental' },
                              { version: 'v1.4.0', channel: 'standard' },
                              { version: 'v1.3.0', channel: 'experimental' },
                              { version: 'v1.3.0', channel: 'standard' },
                              { version: 'v1.2.1', channel: 'experimental' },
                              { version: 'v1.2.1', channel: 'standard' } ]
    steps:
    - uses: actions/checkout@v4
    - id: run-tests
      uses: ./.github/actions/kube-conformance-tests
      with:
        test-type: gateway-api
        conformance-version: ${{ matrix.gateway-api-version.version }}
        conformance-channel: ${{ matrix.gateway-api-version.channel }}

  kube_inference_extension_conformance_tests:
    name: k8s gw API inference extension conformance (gw-api=${{matrix.gateway-api-version.version}}-${{matrix.gateway-api-version.channel}})
    runs-on: ubuntu-22.04
    timeout-minutes: 60
    if: ${{ !github.event.pull_request.draft }}
    strategy:
      fail-fast: false
      matrix:
        kube-version: [ { node: 'v1.34.0@sha256:7416a61b42b1662ca6ca89f02028ac133a309a2a30ba309614e8ec94d976dc5a', kubectl: 'v1.34.1', kind: 'v0.30.0' } ]
        gateway-api-version: [ { version: 'v1.4.0', channel: 'experimental' },
                              { version: 'v1.4.0', channel: 'standard' },
                              { version: 'v1.3.0', channel: 'experimental' },
                              { version: 'v1.3.0', channel: 'standard' },
                              { version: 'v1.2.1', channel: 'experimental' },
                              { version: 'v1.2.1', channel: 'standard' } ]
    steps:
    - uses: actions/checkout@v4
    - id: run-tests
      uses: ./.github/actions/kube-conformance-tests
      with:
        test-type: inference-extension
        enable-inference-extension: true
        conformance-version: ${{ matrix.gateway-api-version.version }}
        conformance-channel: ${{ matrix.gateway-api-version.channel }}

  kube_agent_gateway_conformance_tests:
    name: k8s gw API agent-gateway conformance (gw-api=${{matrix.gateway-api-version.version}}-${{matrix.gateway-api-version.channel}})
    runs-on: ubuntu-22.04
    timeout-minutes: 60
    if: ${{ !github.event.pull_request.draft }}
    env:
      CONFORMANCE_GATEWAY_CLASS: agentgateway
    strategy:
      fail-fast: false
      matrix:
        kube-version: [ { node: 'v1.34.0@sha256:7416a61b42b1662ca6ca89f02028ac133a309a2a30ba309614e8ec94d976dc5a', kubectl: 'v1.34.1', kind: 'v0.30.0' } ]
        gateway-api-version: [ { version: 'v1.4.0', channel: 'experimental' },
                              { version: 'v1.4.0', channel: 'standard' },
                              { version: 'v1.3.0', channel: 'experimental' },
                              { version: 'v1.3.0', channel: 'standard' },
                              { version: 'v1.2.1', channel: 'experimental' },
                              { version: 'v1.2.1', channel: 'standard' } ]
    steps:
    - uses: actions/checkout@v4
    - id: run-tests
      uses: ./.github/actions/kube-conformance-tests
      with:
        test-type: agent-gateway
        additional-helm-values: test/e2e/tests/manifests/agent-gateway-integration.yaml
        conformance-version: ${{ matrix.gateway-api-version.version }}
        conformance-channel: ${{ matrix.gateway-api-version.channel }}
