name: Manual E2E Tests

on:
  workflow_dispatch:
    inputs:
      gateway-api-version:
        description: 'Gateway API version to test against'
        type: string
        default: '1.4'
        required: false
      gateway-api-channel:
        description: 'Gateway API channel (experimental or standard)'
        type: choice
        options:
          - experimental
          - standard
        default: 'experimental'
        required: false
      test-regex:
        description: 'Test regex pattern to run (empty for all tests)'
        type: string
        default: ''
        required: false
      kind-version:
        description: 'KinD version to use'
        type: string
        default: 'v0.30.0'
        required: false
      kubectl-version:
        description: 'kubectl version to use'
        type: string
        default: 'v1.34.1'
        required: false
      istio-version:
        description: 'Istio version to use'
        type: string
        default: '1.25.2'
        required: false

env:
  GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

jobs:
  e2e_tests:
    name: E2E Tests (Gateway API ${{ github.event.inputs.gateway-api-version }} ${{ github.event.inputs.gateway-api-channel }})
    runs-on: ubuntu-22.04
    timeout-minutes: 120
    steps:
    - uses: actions/checkout@v4
    - name: Prep Go Runner
      uses: ./.github/actions/prep-go-runner
    - name: Setup KinD Cluster
      uses: ./.github/actions/setup-kind-cluster
      with:
        kgateway-api-version: ${{ github.event.inputs.gateway-api-version }}
        kgateway-api-channel: ${{ github.event.inputs.gateway-api-channel }}
        cluster-name: "egw-api-e2e-${{ github.event.inputs.gateway-api-version }}-${{ github.event.inputs.gateway-api-channel }}"
        kind-version: ${{ github.event.inputs.kind-version }}
        kubectl-version: ${{ github.event.inputs.kubectl-version }}
        istio-version: ${{ github.event.inputs.istio-version }}
    - id: run-tests
      uses: ./.github/actions/kubernetes-e2e-tests
      with:
        cluster-name: manual-e2e-tests
        test-args: '-v -timeout=120m'
        run-regex: ${{ github.event.inputs.test-regex }}
        istio-version: ${{ github.event.inputs.istio-version }}
        matrix-label: "manual-e2e-${{ github.event.inputs.gateway-api-version }}-${{ github.event.inputs.gateway-api-channel }}"
